// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQSPlRlZxg6kE2C-leMmYw3iYAeVHSA3g',
    appId: '1:611644631347:web:c90016adb1c794d956b646',
    messagingSenderId: '611644631347',
    projectId: 'e-book-aa1d8',
    authDomain: 'e-book-aa1d8.firebaseapp.com',
    storageBucket: 'e-book-aa1d8.appspot.com',
    measurementId: 'G-2STKKEE0HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyKsMktASO-scPEFoA6_kp1hp5cdssnWc',
    appId: '1:611644631347:android:560bf0414119333956b646',
    messagingSenderId: '611644631347',
    projectId: 'e-book-aa1d8',
    storageBucket: 'e-book-aa1d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf80gHp7MYpl2ikYWQy6Y2gwxxmqSpGTA',
    appId: '1:611644631347:ios:0420c1f843dfade056b646',
    messagingSenderId: '611644631347',
    projectId: 'e-book-aa1d8',
    storageBucket: 'e-book-aa1d8.appspot.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf80gHp7MYpl2ikYWQy6Y2gwxxmqSpGTA',
    appId: '1:611644631347:ios:9fe63cf1ca6b7dbc56b646',
    messagingSenderId: '611644631347',
    projectId: 'e-book-aa1d8',
    storageBucket: 'e-book-aa1d8.appspot.com',
    iosBundleId: 'com.example.eBook.RunnerTests',
  );
}
